version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: project-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: project-server
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

volumes:
  postgres_data: